### ISSUE TITLE
Unpublished 'fix for windows compatibility' commit

### ISSUE THREAD

**Issue by davida82** [mattbornski/libphonenumber#12]
Hi,

I see there is a commit called: "fix for windows compatibility" which really enables running libphonenumber on Windows without modifiying anything myself.
Problem is, I don't think it is published yet as I don't get this fix when I do npm install.

Thanks,
David

**Comment by mattbornski** [comment]
published in 0.0.9

**Comment by wOvalle** [comment]
It worked. Thanks!
