### ISSUE TITLE
please don't throw strings

### ISSUE THREAD

**Issue by xjamundx** [mattbornski/libphonenumber#13]
So this kind of thing is considered bad practice in node land. 

```
if (metadata == null) {
    throw 'Invalid region code: ' + regionCode;
}
```

If we throw using `new Error()` you get a stack trace and it follows the more expected pattern of errors in JavaScript.

Would you be open to wrapping all of the `throw {String}` with `new Error()`?

Alternatively, can we update the README with a big fat warning about the potential problem?

Thanks and let me know if you need any help!

**Comment by mattbornski** [comment]
Feel free to submit a PR.  This is a basically a blind import of a pre-existing library, with some node package management applied.

**Comment by xjamundx** [comment]
We have our own wrapper around it locally, so we don't need this, but heads up. It did cause us a bit of trouble :)
