### ISSUE TITLE
Compatibility with browserify

### ISSUE THREAD

**Issue by johnryan** [mattbornski/libphonenumber#17]
Just wondering if this library is intended to be usable with browserify. When I require it I get an error "fs.readFileSync is not a function"

**Comment by Shold** [comment]
You can use original Google's [libphonenumber](https://github.com/googlei18n/libphonenumber). Demo is [here](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html)

**Comment by johnryan** [comment]
Gotcha, I ended up going this route with browserify-shim. Thanks.
