### ISSUE TITLE
Please update to latest and do a doc.

### ISSUE THREAD

**Issue by robertbaker** [mattbornski/libphonenumber#20]
Also need formatLocal function

**Comment by janajri** [comment]
+1 I've had to move onto another fork.

**Comment by sandro-csimas** [comment]
+1

**Comment by ilfa** [comment]
+1

**Comment by YouriT** [comment]
+1

**Comment by YouriT** [comment]
It has been updated to `v7.3.2`.
@robertbaker check wether `formatLocal` is available or not didn't check that.

**Comment by robertbaker** [comment]
@YouriT Unfortunately, I moved onto another project. I will close this since you did update the lib.
